/*
			var p = new Page({title: "Wikipedia:List_of_bots_by_number_of_edits"});
			p.bind('additional', function() {
				var $l = $(p.attributes.text).find('.wikitable').first().find('tr td:nth-child(2)');
				var bots = [];
				_.each($l, function(l) {
					bots.push($(l).text());
				});
				console.log(bots);
				console.log(_.include(bots, 'SmackBot'));
			});
			p.fetchAdditionalData();
 * */
define({
	list : [
	"SmackBot",
 "Cydebot",
 "WP 1.0 bot",
 "Yobot",
 "ClueBot",
 "SineBot",
 "RjwilmsiBot",
 "ClueBot NG",
 "RussBot",
 "BetacommandBot",
 "Xqbot",
 "Lightbot",
 "AlexNewArtBot",
 "Luckas-bot",
 "The Anomebot2",
 "COIBot",
 "Fbot",
 "OrphanBot",
 "AnomieBOT",
 "EmausBot",
 "TXiKiBoT",
 "ListasBot",
 "VeblenBot",
 "Thijs!bot",
 "Kingbotk",
 "Erik9bot",
 "Alaibot",
 "SieBot",
 "VolkovBot",
 "XLinkBot",
 "BOTijo",
 "Xenobot Mk V",
 "D6",
 "SporkBot",
 "MiszaBot III",
 "FrescoBot",
 "Bluebot",
 "Full-date unlinking bot",
 "Mathbot",
 "CmdrObot",
 "YurikBot",
 "VoABot II",
 "ZéroBot",
 "BJBot",
 "DASHBot",
 "Eubot",
 "ArthurBot",
 "AntiVandalBot",
 "CommonsDelinker",
 "ClueBot III",
 "MetsBot",
 "Escarbot",
 "SoxBot",
 "FlaBot",
 "BotMultichill",
 "ImageRemovalBot",
 "DumZiBoT",
 "Polbot",
 "STBotI",
 "Xenobot",
 "Alexbot",
 "KrimpBot",
 "MartinBot",
 "Addbot",
 "MiszaBot II",
 "Kbdankbot",
 "MystBot",
 "HBC AIV helperbot7",
 "HBC Archive Indexerbot",
 "CorenSearchBot",
 "Kotbot",
 "MGA73bot",
 "Citation bot",
 "DrilBot",
 "MiszaBot I",
 "FairuseBot",
 "WildBot",
 "HBC AIV helperbot3",
 "Rambot",
 "ImageTaggingBot",
 "MartinBotIII",
 "DodoBot",
 "Chobot",
 "TinucherianBot",
 "EdwardsBot",
 "Tawkerbot2",
 "WikitanvirBot",
 "ShepBot",
 "H3llBot",
 "Citation bot 1",
 "Detroiterbot",
 "SkiersBot",
 "JAnDbot",
 "RFC bot",
 "AAlertBot",
 "CheMoBot",
 "SatyrBot",
 "タチコマ robot",
 "GrouchoBot",
 "Reedy Bot",
 "Chris G Bot 3",
 "Tawkerbot",
 "Pearle",
 "Femto Bot",
 "DarknessBot",
 "LucienBOT",
 "Alphachimpbot",
 "Ganeshbot",
 "718 Bot",
 "TedderBot",
 "Zorrobot",
 "DumbBOT",
 "PseudoBot",
 "HagermanBot",
 "Numbo3-bot",
 "AvicBot",
 "AlleborgoBot",
 "Rei-bot",
 "Robbot",
 "DFBot",
 "RobotG",
 "OKBot",
 "The wubbot",
 "HBC AIV helperbot5",
 "MiszaBot",
 "CactusBot",
 "LaaknorBot",
 "BrownBot",
 "BryanBot",
 "ChuispastonBot",
 "ProteinBoxBot",
 "NoomBot",
 "CanisRufus",
 "RM bot",
 "DeltaQuadBot",
 "Wikinews Importer Bot",
 "Redirect fixer",
 "STBot",
 "GimmeBot",
 "ArticleAlertbot",
 "PhotoCatBot",
 "Erwin85Bot",
 "GA bot",
 "SQLBot",
 "LaraBot",
 "Werdnabot",
 "Scsbot",
 "RibotBOT",
 "DSisyphBot",
 "Ralbot",
 "SoxBot V",
 "Amirobot",
 "STTWbot",
 "MelonBot",
 "BAGBot",
 "DYKUpdateBot",
 "MalafayaBot",
 "JL-Bot",
 "Staeckerbot",
 "FoxBot",
 "Ptbotgourou",
 "DragonBot",
 "Maelgwnbot",
 "Uncle G's major work 'bot",
 "Shadowbot3",
 "Drinibot",
 "BotMultichillT",
 "Kumi-Taskbot",
 "Idioma-bot",
 "MarshBot",
 "Snotbot",
 "Mr.Z-bot",
 "DefaultsortBot",
 "ClueBot II",
 "Tangobot",
 "Thadius856AWB",
 "Helpful Pixie Bot",
 "WatchlistBot",
 "Gdrbot",
 "Legobot",
 "DOI bot",
 "SashatoBot",
 "TobeBot",
 "AntiSpamBot",
 "DyceBot",
 "SharedIPArchiveBot",
 "KamikazeBot",
 "TuHan-Bot",
 "Sandbot",
 "Muro Bot",
 "DinoBot2",
 "AP.BOT",
 "BotanyBot",
 "Sethbot",
 "SassoBot",
 "PotatoBot",
 "Jogersbot",
 "Petan-Bot",
 "SilvonenBot",
 "MenasimBot",
 "DYKHousekeepingBot",
 "RedBot",
 "WinBot",
 "STBotD",
 "HBC AIV helperbot2",
 "PixelBot",
 "EarwigBot",
 "Eskimbot",
 "Ohms Law Bot",
 "D'ohBot",
 "DHN-bot",
 "BogBot",
 "MastiBot",
 "J Milburn Bot",
 "SteveBot",
 "Obersachsebot",
 "PipepBot",
 "Δbot",
 "Scepbot",
 "CommonsNotificationBot",
 "BOTarate",
 "Rubinbot",
 "Guanabot",
 "CapitalBot",
 "KevinBot",
 "People-photo-bot",
 "SPCUClerkbot",
 "HBC NameWatcherBot",
 "CSDWarnBot",
 "Ripchip Bot",
 "AMbot",
 "SoxBot III",
 "VoABot",
 "Curpsbot-unicodify",
 "JeffGBot",
 "SDPatrolBot",
 "Commander Keane bot",
 "TaBOT-zerem",
 "MifterBot I",
 "HBC AIV helperbot",
 "KingpinBot",
 "Android Mouse Bot 2",
 "Mjbmrbot",
 "LivingBot",
 "Whobot",
 "PbBot",
 "BG19bot",
 "Gnome (Bot)",
 "BoxCrawler",
 "KarlsenBot",
 "COBot",
 "Thehelpfulbot",
 "Broadbot",
 "Phe-bot",
 "Comics-awb",
 "A4bot",
 "DYKadminBot",
 "JoeBot",
 ".anacondabot",
 "DASHBotAV",
 "RonaldBot",
 "AfDBot",
 "Snowbot",
 "JhsBot",
 "RBot",
 "MerlIwBot",
 "MPUploadBot",
 "^demonBot2",
 "John Bot",
 "Svenbot",
 "AWeenieBot",
 "HBC AIV helperbot4",
 "Pegasusbot",
 "HRoestBot",
 "OverlordQBot",
 "OgreBot",
 "Rezabot",
 "AndersBot",
 "WikiStatsBOT",
 "SuggestBot",
 "Tawkerbot4",
 "MessedRobot",
 "BernsteinBot",
 "SpBot",
 "BOT-Superzerocool",
 "EmxBot",
 "AlnoktaBOT",
 "Dinamik-bot",
 "BenzolBot",
 "Legobot II",
 "SoxBot II",
 "BorgardeBot",
 "SoxBot IV",
 "Vina-iwbot",
 "Seedbot",
 "Zwobot",
 "JaGaBot",
 "Rschen7754bot",
 "Grafikbot",
 "Taxobot 1",
 "SQLBot-Hello",
 "CobraBot",
 "AdminStatsBot",
 "Locobot",
 "LordAnubisBOT",
 "MBisanzBot",
 "Arbitrarily0Bot",
 "Kyle the bot",
 "CarsracBot",
 "LostBot",
 "EdoBot",
 "SelketBot",
 "One bot",
 "UnCatBot",
 "ChzzBot II",
 "Sagabot",
 "Synthebot",
 "DPL bot",
 "XLerateBot",
 "XyBot",
 "Roboto de Ajvol",
 "NW557Bot",
 "MadmanBot",
 "Giggabot",
 "RobotE",
 "KnightRider",
 "DorganBot",
 "KocjoBot",
 "WPArkansas Bot",
 "GrinBot",
 "Fluxbot",
 "MondalorBot",
 "CounterVandalismBot",
 "NjardarBot",
 "MauritsBot",
 "WeggeBot",
 "MifterBot",
 "Rick Bot",
 "Jumbuck",
 "NetBot",
 "Zorglbot",
 "Alph Bot",
 "KevinalewisBot",
 "RebelRobot",
 "MerlLinkBot",
 "Lucasbfrbot",
 "FlBot",
 "JdforresterBot",
 "RaptureBot",
 "Chem-awb",
 "Taxobot 7",
 "ZhBot",
 "CitationCleanerBot",
 "Tsca.bot",
 "Citation bot 2",
 "Anybot",
 "Bot0612",
 "Almabot",
 "LinkFA-Bot",
 "ArkyBot",
 "TechBot",
 "AccReqBot",
 "Mairibot",
 "CopyToWiktionaryBot",
 "RoryBot",
 "Bota47",
 "ChzzBot IV",
 "PeerReviewBot",
 "Vagobot",
 "BotKung",
 "Ligulembot",
 "Chlewbot",
 "RockfangBot",
 "AkhtaBot",
 "Crypticbot",
 "Luasóg bot",
 "JackieBot",
 "SamatBot",
 "Syrcatbot",
 "28bot",
 "CocuBot",
 "StigBot",
 "KslotteBot",
 "ArticlesForCreationBot",
 "John Bot III",
 "Darkicebot",
 "Anchor Link Bot",
 "BHGbot",
 "MessageDeliveryBot",
 "McM.bot",
 "El bot de la dieta",
 "Louperibot",
 "JCbot",
 "Chris G Bot",
 "Peelbot",
 "VVVBot",
 "Pageview bot",
 "Wherebot",
 "GargoyleBot",
 "VWBot",
 "BrokenAnchorBot",
 "KittyBot",
 "HtonlBot",
 "EarwigBot I",
 "VixDaemonBot",
 "Pokbot",
 "FlagBot",
 "HerculeBot",
 "SpellingBot",
 "PDFbot",
 "Jitse's bot",
 "LatitudeBot",
 "Aksibot",
 "Estirabot",
 "Maksim-bot",
 "Nallimbot",
 "WebCiteBOT",
 "AFD Bot",
 "Bibcode Bot",
 "GurchBot",
 "ImageBacklogBot",
 "DixonDBot",
 "ClueBot VI",
 "WelcomerBot",
 "Uncle G's 'bot",
 "PNG crusade bot",
 "TPO-bot",
 "DomBot",
 "Ebrambot",
 "Margosbot",
 "StatusBot",
 "EarwigBot III",
 "EBot IV",
 "DeadBot",
 "Purbo T",
 "Le Pied-bot",
 "NedBot",
 "BodhisattvaBot",
 "CountryBot",
 "FileBot",
 "AfDStatBot",
 "StatisticianBot",
 "MTSbot",
 "Mentibot",
 "ChenzwBot",
 "EssjayBot",
 "BenoniBot",
 "SEWilcoBot",
 "Jotterbot",
 "YonaBot",
 "Martin's bot",
 "WikiDreamer Bot",
 "NTBot",
 "HasharBot",
 "LawBot",
 "Kakashi Bot",
 "Gerakibot",
 "Milk's Favorite Bot",
 "ENewsBot",
 "Lt-wiki-bot",
 "WolterBot",
 "Android Mouse Bot 3",
 "EBot II",
 "XZeroBot",
 "RefDeskBot",
 "BotPuppet",
 "CohesionBot",
 "PlangeBot",
 "TuvicBot",
 "Andrea105Bot",
 "TinucherianBot II",
 "Hxhbot",
 "Skumarlabot",
 "AmphBot",
 "Beastie Bot",
 "TjBot",
 "ClickBot",
 "GeorgeMoneyBot-status",
 "ZsinjBot",
 "NukeBot",
 "KaiserbBot",
 "PlankBot",
 "Nobot",
 "HBC AIV helperbot 8",
 "NolBot",
 "WuBot",
 "Ugur Basak Bot",
 "Pathosbot",
 "Mgmbot",
 "FANSTARbot",
 "SelectionBot",
 "HersfoldArbClerkBot",
 "ARSBot",
 "CrimsonBot",
 "Adlerbot",
 "JamietwBot",
 "SundarBot",
 "Android Mouse Bot",
 "SoxBot VI",
 "AdambroBot",
 "MenoBot",
 "ClueBot Commons",
 "OldMedcabBot",
 "Image Screening Bot",
 "Sahimrobot",
 "GhalyBot",
 "ToePeu.bot",
 "PolarBot",
 "SoxBot VIII",
 "RoboMaxCyberSem",
 "AstaBOTh15",
 "MonoBot",
 "DYKBot",
 "ChandlerMapBot",
 "R Delivery Bot",
 "Yonidebot",
 "Movses-bot",
 "DcoetzeeBot",
 "People-n-photo-bot",
 "Albambot",
 "Hazard-Bot",
 "Swimmingbot-awb",
 "DirlBot",
 "Elissonbot",
 "BepBot",
 "Citation bot 3",
 "MartinBotIV",
 "Vini 17bot5",
 "ClueBot IV",
 "MMABot",
 "Taxobot 2",
 "PDBbot",
 "Admrbot",
 "ImageTagBot",
 "MuZebot",
 "WarddrBOT",
 "H92Bot",
 "Tanhabot",
 "Diego Grez Bot",
 "Signpost Book Bot",
 "Byrialbot",
 "FiriBot",
 "Bot-Schafter",
 "HiW-Bot",
 "Bot523",
 "Philosopher-Bot",
 "DustyBot",
 "Chrisbot",
 "BetBot",
 "Blood Oath Bot",
 "TottyBot",
 "Kl4m-AWB",
 "RFRBot",
 "AmeliorationBot",
 "Bikabot",
 "LDBot",
 "NrhpBot",
 "Bocianski.bot",
 "HotArticlesBot",
 "FaleBot",
 "Lucia Bot",
 "Zxabot",
 "CrazynasBot",
 "IPTaggerBot",
 "Rfambot",
 "Ver-bot",
 "HarrivBOT",
 "Ocobot",
 "KolBot",
 "PascalBot",
 "Kwjbot",
 "SpillingBot",
 "CricketBot",
 "SoxBot X",
 "RobotJcb",
 "Kasirbot",
 "ListGenBot",
 "WikiBotas",
 "Wybot",
 "Peti610botH",
 "Plasticbot",
 "FPBot",
 "Robert SkyBot",
 "Android Mouse Bot 4",
 "GedawyBot",
 "GrooveBot",
 "NekoBot",
 "RoboServien",
 "SMS Bot",
 "SoxBot VII",
 "AzaBot",
 "BotdeSki",
 "Slobot",
 "Eivindbot",
 "AilurophobiaBot",
 "DeadLinkBOT",
 "MagnusA.Bot",
 "Kisbesbot",
 "O bot",
 "Manishbot",
 "Snaevar-bot",
 "SheepBot",
 "NodBot",
 "Nixbot",
 "Lowercase sigmabot",
 "MastersBot",
 "GracenotesBot",
 "AntiAbuseBot",
 "Janna Isabot",
 "JVbot",
 "7SeriesBOT",
 "AudeBot",
 "Legobot III",
 "DinoBot",
 "Botpankonin",
 "Ficbot",
 "SwiftBot",
 "Yet Another Redirect Cleanup Bot",
 "Rameshngbot",
 "SDPatrolBot II",
 "EBot",
 "AndreasJSbot",
 "Anibot",
 "NobelBot",
 "Nono le petit robot",
 "Mulder416sBot",
 "TARBOT",
 "MCBot",
 "WODUPbot",
 "NeuRobot",
 "Antischmitzbot",
 "Taxobot",
 "VP-bot",
 "ChzzBot",
 "WaldirBot",
 "ElMeBot",
 "Stwalkerbot",
 "TTObot",
 "AutocracyBot",
 "MartinBotII",
 "MediationBot",
 "GnawnBot",
 "MandelBot",
 "UcuchaBot",
 "Caypartisbot",
 "PsychAWB",
 "TypoBot",
 "Analphabot",
 "Newsletterbot",
 "Danumber1bot",
 "Robotic Garden",
 "Dark Shikari Bot",
 "AnomieBOT II",
 "BotCompuGeek",
 "SvickBOT",
 "NeraBot",
 "AlptaBot",
 "Halibott",
 "VsBot",
 "RscprinterBot",
 "GZ-Bot",
 "Diligent Terrier Bot",
 "Riccardobot",
 "Kal-El-Bot",
 "Luuvabot",
 "UncatTemplateBot",
 "Botx",
 "BendelacBOT",
 "DrFO.Tn.Bot",
 "IluvatarBot",
 "Selmobot",
 "DavidWSBot",
 "HujiBot",
 "BenjBot",
 "BoricuaBot",
 "AsgardBot",
 "Minsbot",
 "Sumibot",
 "Acebot",
 "Madhubot",
 "JJBot",
 "RSElectionBot",
 "FritzpollBot",
 "DEagleBot",
 "KaldariBot",
 "AHbot",
 "NilfaBot",
 "Amolbot",
 "Simplebot",
 "AloysiusLiliusBot",
 "EddieBot",
 "Manubot",
 "OrophinBot",
 "Citation bot 4",
 "AZatBot",
 "Denbot",
 "Milk's Favorite Bot II",
 "Pfft Bot",
 "ChessBOT",
 "SVGBot",
 "VeinorBot",
 "Rtz-bot",
 "QOTDBot",
 "MrVanBot",
 "PaievBot",
 "IcalaniseBot",
 "QualiaBot",
 "WoodwardBot",
 "KuduBot",
 "DeliveryBot",
 "LSG1-Bot",
 "Egmontbot",
 "Orphaned talkpage deletion bot",
 "XeBot",
 "EleferenBot",
 "JMuniBot",
 "AvicBot2",
 "BücherBot",
 "Naudefjbot",
 "SusBot",
 "Botryoidal",
 "MedcabBot",
 "MichaelBillingtonBot",
 "Innocent iwbot",
 "MalarzBOT",
 "ChzzBot III",
 "HMBot",
 "ReigneBOT",
 "Kgsbot",
 "DottyQuoteBot",
 "OpenlibraryBot",
 "SandgemBot",
 "Kaspobot",
 "Kumar Appaiah Bot",
 "AswnBot",
 "MauchoBot",
 "WMUKBot",
 "SharafBot",
 "Rabbot",
 "Pattonbot",
 "The Auto-categorizing Robot",
 "SamuraiBot",
 "StormBot",
 "ZedlikBot",
 "DusterBot",
 "H2Bot",
 "EagleAstroidBot",
 "Rob110178bot",
 "AWBCPBot",
 "Homobot",
 "SVnaGBot1",
 "Lockalbot",
 "GeorgeMoneyBot",
 "StatsBot",
 "Fettgesicht",
 "EBot III",
 "CSBot",
 "Cherybot",
 "TaeBot",
 "RFC posting script",
 "Project Messenger Bot",
 "MotinBot",
 "WilhelmBot",
 "DinoSizedBot",
 "DanielBot",
 "DarioBot",
 "Bersibot",
 "Sgeo-BOT",
 "ViskonBot",
 "DvyBot",
 "ArbComBot",
 "JerryBot",
 "Amalthea (bot)",
 "UltraBot",
 "Z-BOT",
 "YekratsBot",
 "R. Hillgentleman",
 "OrBot",
 "CataBotTsirel",
 "Smallbot",
 "Orphaned image deletion bot",
 "MichaelkourlasBot",
 "Mihas-bot",
 "Danielfolsom2.bot",
 "SPPatrolBot",
 "Dpkbot",
 "M-Bot",
 "CleanupListingBot",
 "SpebiBot",
 "AwOcBot",
 "Town-bot",
 "TorNodeBot",
 "CloudNineBot",
 "SebrevBOT",
 "SpellCheckerBot",
 "Wikipedia Signpost",
 "AEBot",
 "MediaWiki default",
 "Heikobot",
 "WASDbot",
 "NVS(bot)",
 "CommonsNotification",
 "CwraschkeDataBot",
 "WalkingSoulBot",
 "Nomenclaturebrowser",
 "PC78-bot",
 "Wpp research bot",
 "EyeEightDestroyerBot",
 "WillieBot",
 "KyluBot",
 "ChrisSalij Bot",
 "Taxobot 6",
 "Taxobot 3",
 "Geimas5Bot",
 "BsherrAWBBOT",
 "MetaplasticityBot",
 "AlekseyBot",
 "Taxobot (usurped)",
 "JatBot",
 "SlakrBot",
 "Non-Free Content Compliance Bot",
 "Collabsearch",
 "ProcseeBot"]
});
